export const doctorSpecialties = [
  "Cardiologist",
  "Dermatologist",
  "Endocrinologist",
  "Gastroenterologist",
  "Hematologist",
  "Nephrologist",
  "Neurologist",
  "Oncologist",
  "Ophthalmologist",
  "Orthopedic Surgeon",
  "Otolaryngologist (ENT Specialist)",
  "Pediatrician",
  "Psychiatrist",
  "Pulmonologist",
  "Radiologist",
  "Rheumatologist",
  "Urologist",
  "Allergist/Immunologist",
  "Anesthesiologist",
  "Emergency Medicine Specialist",
  "Family Medicine Physician",
  "General Surgeon",
  "Geriatrician",
  "Infectious Disease Specialist",
  "Internal Medicine Physician",
  "Obstetrician/Gynecologist (OB/GYN)",
  "Pathologist",
  "Podiatrist",
  "Plastic Surgeon",
  "Sports Medicine Specialist",
];

export const doctors = [
  {
    id: 1,
    name: "Dr. Sarah Khan",
    appointmentTime: "10:00 AM - 2:00 PM",
    fees: 1500,
    category: "Cardiologist",
    hospital: "City Heart Clinic",
    gender: "Female",
  },
  {
    id: 2,
    name: "Dr. Ahmed Raza",
    appointmentTime: "9:00 AM - 12:00 PM",
    fees: 1200,
    category: "Dermatologist",
    hospital: "Skin Care Hospital",
    gender: "Male",
  },
  {
    id: 3,
    name: "Dr. Farah Ali",
    appointmentTime: "11:00 AM - 4:00 PM",
    fees: 1800,
    category: "Endocrinologist",
    hospital: "Endo Wellness Center",
    gender: "Female",
  },
  {
    id: 4,
    name: "Dr. Imran Qureshi",
    appointmentTime: "8:00 AM - 1:00 PM",
    fees: 1400,
    category: "Gastroenterologist",
    hospital: "Digestive Health Clinic",
    gender: "Male",
  },
  {
    id: 5,
    name: "Dr. Sana Malik",
    appointmentTime: "10:00 AM - 3:00 PM",
    fees: 1600,
    category: "Neurologist",
    hospital: "Neuro Care Hospital",
    gender: "Female",
  },
  {
    id: 6,
    name: "Dr. Adil Nawaz",
    appointmentTime: "9:00 AM - 12:30 PM",
    fees: 1300,
    category: "Orthopedic Surgeon",
    hospital: "Ortho Specialist Clinic",
    gender: "Male",
  },
  {
    id: 7,
    name: "Dr. Maria Yousaf",
    appointmentTime: "12:00 PM - 5:00 PM",
    fees: 1700,
    category: "Pediatrician",
    hospital: "Children's Health Hospital",
    gender: "Female",
  },
  {
    id: 8,
    name: "Dr. Faisal Hussain",
    appointmentTime: "1:00 PM - 6:00 PM",
    fees: 2000,
    category: "Psychiatrist",
    hospital: "Mental Wellness Clinic",
    gender: "Male",
  },
  {
    id: 9,
    name: "Dr. Anam Shah",
    appointmentTime: "8:00 AM - 12:00 PM",
    fees: 1600,
    category: "Pulmonologist",
    hospital: "Lung Care Center",
    gender: "Female",
  },
  {
    id: 10,
    name: "Dr. Ali Kamal",
    appointmentTime: "3:00 PM - 7:00 PM",
    fees: 2200,
    category: "Oncologist",
    hospital: "Cancer Treatment Hospital",
    gender: "Male",
  },
];

export const currentUser = {
  name: "Siddique Ahmed",
  role: "doctor",
};
